### ISSUE TITLE
[1.12.2]Incompatible with Inventory Bogo Sorter

### ISSUE THREAD

**Issue by ghost** [Giant-Salted-Fish/Key-Binding-Patch#2]
[Mod link](https://www.curseforge.com/minecraft/mc-mods/inventory-bogosorter)

Overview: Unable to use shortcut keys to sort the backpack, even if the default key position (middle click) is modified

**Comment by Giant-Salted-Fish** [comment]
I suggest that you take a try with the latest version and see if this problem still presents. And if it does, then it should mean that Bogo Sorted embedded some specifial key triggering code that could have conflict with this mod. And this could be considered more of a bug in Bogo Sort rather than in Key Binding Patch.

**Comment by Giant-Salted-Fish** [comment]
I have tried out and did reproduce this issue when testing with [Inventory BogoSorter − 1.4.8](https://www.curseforge.com/minecraft/mc-mods/inventory-bogosorter/files/5162169). Now fixed in KBP v1.3.3.0. Please update to the lateset version.
